config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'foods#index'

  resources :users, only: %i[index show]

  resources :recipes, only: %i[index show new create destroy] do
    resources :recipefoods, only: %i[index show new create destroy]
    resources :general_shopping_list, only: %i[index]
  end

  resources :foods, only: %i[index show new create destroy] do
  end

  get 'public_recipes', to: 'recipes#public', as: 'public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # return unless user.present?
    # can :read, :all
    # return unless user.admin?
    # can :manage, :all
    can :read, :all
    can :manage, Recipe, user_id: user.id
    can :manage, Food
    can :manage, Recipefood
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipefoods, dependent: :destroy

  has_many :recipes, through: :recipefoods

  validates :name, presence: true, length: { minimum: 3, maximum: 250 }
  validates :measurement_unit, presence: true, length: { maximum: 250 }
  validates :price, presence: true
  validates :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipefoods, dependent: :destroy

  has_many :foods, through: :recipefoods

  validates :name, presence: true, length: { minimus: 3, maximum: 250 }
end

app/models/recipefood.rb
class Recipefood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])

    @total_item_to_buy = 0
    @missing_foods = []
    @total_price = 0

    @recipe.recipefoods.each do |ingredient|
      food = Food.find(ingredient.food_id)

      next if ingredient.quantity <= food.quantity

      @total_item_to_buy += 1
      @quantity = ingredient.quantity - food.quantity
      @missing_foods << ingredient
      @total_price += (ingredient.quantity - food.quantity) * food.price
    end
  end
end

app/controllers/recipefoods_controller.rb
class RecipefoodsController < ApplicationController
  load_and_authorize_resource
  def new
    @foods = current_user.foods
    @recipe = Recipe.find(params[:recipe_id])
    @recipefood = Recipefood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipefood = Recipefood.new(recipefood_params)
    @recipefood.recipe = @recipe

    if @recipefood.save
      redirect_to recipe_path(@recipe), notice: 'New ingredient was successfully added.'
    else
      flash[:alert] = 'New Ingredient adding Failed. Please try again.'
    end
  end

  def destroy
    @recipefood = Recipefood.find(params[:id])

    unless @recipefood.recipe.user == current_user
      flash[:alert] = 'You do not have access to delete the ingredient belongs to other Users.'
      return redirect_to recipes_path
    end

    if @recipefood.destroy
      flash[:notice] = 'Ingredient was successfully removed.'
    else
      flash[:alert] = 'Ingredient removal Failed. Please try again.'
    end
    redirect_to recipes_path
  end

  def recipefood_params
    params.require(:recipefood).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipefoods = Recipefood.where(recipe_id: @recipe.id).includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:sucess] = 'Recipe successfully Created'
      redirect_to recipes_path
    else
      flash.now[:error] = 'Error creating recipe'
      render new_recipe_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipe_path
  end

  def public
    @public_recipes = Recipe.where(public: true).order('created_at DESC').includes(:user, :recipefoods)

    @totals = {}

    @public_recipes.each do |pub|
      total = 0
      Recipefood.where(recipe_id: pub.id).each do |rec_food|
        total += rec_food.quantity * rec_food.food.price
      end
      @totals[pub.id] = total
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div>


<span class="new-food"><%= link_to "Add Food", new_food_path,class: "Add-food" %></span>

<div id="foods">
    <table class="food-table">
    <tr>
    <th>Food</th>
    <th>Measurement unit</th>
    <th>Unit price</th>
    <th>Actions</th>
    </tr>
    <% @foods.each do |food| %>
    <tr>
    <td><%= food.name.capitalize %></td>
    <td><%= food.measurement_unit %></td>
    <td><%= food.price %></td>
    <td><%= link_to "Delete" , food, data: { turbo_method: :delete,turbo_confirm: 'are you sure to delete?'}, class: "remove-link" %></td>
    <tr>
     <% end %>
    </table>

</div>
</div>

app/views/foods/new.html.erb
<%# # Showing error messages for validations %>
<%= form_with model: @food , url: foods_path do |form| %>


  <% if @food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@food.errors.count, "error") %> Please make sure to follow these requirements:</h2>

      <ul>
        <% @food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <%# # Showing error messages for failures with flash %> 
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<div class="container">
    <h1> Food Form</h1>
   <div class="row">
       <div class="col-25">
            <%=form.label :name%>
       </div>
        <div class="col-75">
             <%=form.text_field :name%>
        </div>
    </div>

    <div class="row">
        <div class="col-25">
           <%=form.label :measurement_unit%>
        </div>
       <div class="col-75">
        <%=form.text_field :measurement_unit%>
        </div>
      </div>


     <div class="row">
        <div class="col-25">
             <%= form.label :quantity %>
        </div>
       <div class="col-75">
             <%= form.number_field :quantity %>
        </div>
    </div>

     <div class="row">
        <div class="col-25">
             <%= form.label :price %>
        </div>
       <div class="col-75">
             <%= form.number_field :price %>
        </div>
    </div>

 <div class="row">
    <%= form.submit %>
    </div>
</div>
<%end%>

app/views/general_shopping_list/index.html.erb
<div>
    <h2>Shopping List</h2>

    <div class="shopping-list-details">
        <p>Amount food items to buy: <%= @total_item_to_buy %> </p>
        <p>Total value of food needed: $ <%= @total_price %> </p>
    </div>

      <table>
       <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
      </tr>
     
     <% @missing_foods.each do |recipefood| %>
     <tr>
       <td> <%= recipefood.food.name%> </td>
       <td> <%= @quantity %> </td>
       <td> <%= @quantity * recipefood.food.price %>$ </td>
     <% end %>
     
     </table>
</div>

app/views/layouts/_navbar.html.erb
<nav class="nav-class">
    <h1 class="Heading">Shopping recipes app</h1>
<div class="nav-style">
 <div class="nav-style-links">
    <% if current_user %>
    <%= link_to "Recipes", recipes_path, class: "text-blue" %>
    <%= link_to "Foods", foods_path, class: "text-blue" %>
  <% end %>

  <%= link_to "Public Recipes", "/public_recipes", class: "active"  %>
 </div>


<div>
    <% if current_user %>
      <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "destroy-session text-blue" %>
    <% else %>
      <% if current_page?(new_user_session_path) %>
        <%= link_to "Sign up", new_user_registration_path, class: "signup text-blue " %>
      <% elsif current_page?(new_user_registration_path) %>
        <%= link_to "Sign in", new_user_session_path, class: "signin text-blue" %>
      <% end %>
    <% end %>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "navbar.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="app-controller">
     <%= yield %>
  </div>
  </body>
</html>

app/views/recipefoods/_form.html.erb
<%= form_with model: @recipefood, url: recipe_recipefoods_path do |form| %>

<%# # Showing error messages for validations %> 
  <% if recipefood.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipefood.errors.count, "error") %> prohibited this recipefood from being saved:</h2>

      <ul>
        <% recipefood.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container-login">
        <div class="row">
          <div class="col-25">
              <%= form.label :quantity, style: "display: block" %>
           <div class="col-75">
             <%= form.number_field :quantity %>
           </div>
          </div>

  <div class="col-75">
          <div class="col-25">
             <%= form.label :food_id, "Food"%> 
          </div>
            <div class="col-75">
               <%= form.collection_select(:food_id, @foods, :id, :name) %>
           </div>
     </div>
       <div class="col-75">
             <%= form.submit "Add ingredient" %>
      </div>
    </div>
<% end %>

app/views/recipefoods/_recipefood.html.erb
<div id="<%= dom_id recipefood %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipefood.quantity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipefood.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipefood.food_id %>
  </p>

</div>

app/views/recipefoods/edit.html.erb
<h1>Editing recipefood</h1>

<%= render "form", recipefood: @recipefood %>

<br>

<div>
  <%= link_to "Show this recipefood", @recipefood %> |
  <%= link_to "Back to recipefoods", recipefoods_path %>
</div>

app/views/recipefoods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipefoods</h1>

<div id="recipefoods">
  <% @recipefoods.each do |recipefood| %>
    <%= render recipefood %>
    <p>
      <%= link_to "Show this recipefood", recipefood %>
    </p>
  <% end %>
</div>

<%= link_to "New recipefood", new_recipefood_path %>

app/views/recipefoods/new.html.erb
<h1 clasa = "add-friuts">Add ingredient to <%=@recipe.name %> </h1>
 <%# # Showing error messages for failures with flash %> 
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<%= render "form", recipefood: @recipefood %>

<br>

<div>
  <%= link_to "Back to recipefoods", recipe_path(@recipe.id) %>
</div>

app/views/recipefoods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipefood %>

<div>

  <%= link_to "Back to recipefoods", recipe_path(@recipe) %>

  <%= button_to "Destroy this recipefood", @recipefood, method: :delete %>
</div>

app/views/recipes/index.html.erb
<div class="recipes-container">

  <p class="new-recipe"> <%= link_to 'Add new recipe', new_recipe_path, class: "add-ingredient" %> </p>
  
    <% @recipes.each do |recipe| %>
    <div class="recipes">
      <p class="recipes-remove">
      <%= link_to "#{recipe.name.capitalize}", recipe_path(recipe), class:"recipe-name"  %>

      <% if can? :delete, recipe %>
       <%= link_to 'Remove', recipe_path(recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "remove-button"%>
      <% end %>

     </p>
     <div class="description">
        <p class="d-detail"> Description for recipe <%= recipe.name.capitalize %> </p>
        <p class="d-detail"> <%= recipe.description %> </p>
     </div>
    </div>
    <% end %>
   
</div>

app/views/recipes/new.html.erb
<%# # Showing error messages for validations %> 
<div>
  <% if @recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe.errors.count, "error") %> Please make sure you follow these requirements:</h2>
      <ul>
        <% @recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <%# # Showing error messages for failures with flash %> 
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

 <%= form_with model: @recipe, url: recipes_path, method: :post, local: true do |form| %>
  <div class="container-login">
    <div class="center-recipe">
        <div class="row">
          <div class="col-25">
               <%= form.label :name, 'Name' %> 
          </div>
        <div class="col-75">
              <%= form.text_field :name %> 
          </div>
      </div>
  <div class="row">
          <div class="col-25">
        <%= form.label :preparation_time, 'Preparation time in Hour' %> 
      </div>
       <div class="col-75">
           <%= form.number_field :preparation_time %> 
        </div>
  </div>
   <div class="row">
          <div class="col-25">
            <%= form.label :cooking_time, 'Cooking time in Hour' %> 
          </div>
          <div class="col-75">
             <%= form.number_field :cooking_time %> 
          </div>
      </div>
     <div class="row">
          <div class="col-25">
            <%= form.label :public, 'Public' %>
          </div>
           <div class="col-75">
             <%= form.check_box :public %> 
            </div>
       </div>

              <div class="row">
                  <div class="col-25">
                       <%= form.label :description, 'Description' %> <br/>
                    </div>
                  <div class="col-75">
                    <%= form.text_area :description, size: "27x5"  %> <br/><br/>
                  </div>
               </div>
            <div>
               <div class="row">
           <%= form.submit %> <br/>
            </div>
<% end %>
</div>

app/views/recipes/public.html.erb
<div class="public-class">
<h2>Public recipes </h2>
  <% @public_recipes.each do |public_recipe| %>
  <div class="public-container">
    <div class="public-details">
      <p> <strong> <%= link_to "#{public_recipe.name.capitalize}", recipe_path(public_recipe.id), class: "names" %> </strong> </p>
      <p>By: <%= public_recipe.user.name.capitalize %> </p>
    </div>

    <div class="public-prices">
      <p> Total food items: <%= public_recipe.recipefoods.length %> </p>
        
   <p> Total price: $ <%= @totals[public_recipe.id] %>
    </p>

    </div>
  </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
     
<div class="recipe-container">     
     <h2>Recipe <%= @recipe.id %> :  <%= @recipe.name.capitalize %> </h2>

  <div class="recipe-detail">
    <div class="recipes-side">
     <p>Preparation time:   <%= @recipe.preparation_time %> 
          <% if @recipe.preparation_time > 1 %>
               <%= 'hours '%> 
          <% else %> 
               <%= 'hour'%>
          <% end %>
      </p>

     <p>Cooking time:   <%= @recipe.cooking_time %>
       <% if @recipe.cooking_time > 1 %>
               <%= 'hours'%> 
          <% else %> 
               <%= 'hour'%>
          <% end %>
     </p>

     <p>Steps go here ...</p>
   </div>

     <div class="recipes-public">
     <p>Public</p>
      <label class="switch ">
          <input type="checkbox">
          <span class="slider round"></span>
     </label>
     </div>

  </div>

 <div class="generate-buttons">
   <p><%= link_to 'Generate shopping list', recipe_general_shopping_list_index_path(@recipe), class: "shopping-list" %></p>
   <p><%= link_to 'Add ingredient', new_recipe_recipefood_path(@recipe), class: "add-ingredient" %></p>
 </div>
 <hr>

<div>
     
</div>
     <table>
       <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
      </tr>
     
     <% @recipefoods.each do |recipefood| %>
     <tr>
       <td> <%= recipefood.food.name%> </td>
       <td> <%= recipefood.quantity %> </td>
       <td> <%= recipefood.quantity * recipefood.food.price %>$ </td>
       <td> <%= link_to 'Modify', recipes_path(@recipe), class: "edit-link" %>  <%= link_to 'Remove', recipe_recipefood_path(@recipe, recipefood),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "remove-link" %></td>
     </tr>
     <% end %>
     
     </table>
</div>    

app/views/users/index.html.erb
<p>
 <% @users.each do |user| %> 
  <%= user.name %>
  <% end %>
</p>